name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news"
database_id = "b7935d3f-2bd5-43a5-b9f3-88638ded730e"
