name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news-db"
database_id = "508a36ae-a967-4ae2-874b-d517dd558fa7"
